name: Deploy Vite App

on:
  push:
    branches: [ main ]         # 푸시하는 브랜치명 다르면 여기 바꾸기

defaults:
  run:
    working-directory: day01_0825/Ex_proj   # ← 앱 폴더 경로

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci || npm install
      - run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: day01_0825/Ex_proj/dist   # ← 빌드 결과 경로
